### ISSUE TITLE
Retry the http request upon refresh

### ISSUE THREAD

**Issue by feinstein** [felangel/fresh#106]
I looked at the code, maybe I missed it and I apologise, but it would be better if the library had an option to retry the same http request if it detected a token refresh was necessary (e.g. Got a 401 error, did a refresh, then send the old request again with the new token).

Also include a timer to try to refresh before expiring, so there's less chance for an http request will fail.

**Comment by uzuki-P** [comment]
Upon checking out the code and also some testing using [Alice](https://github.com/jhomlala/alice/tree/master), fresh actually did [resend the request](https://github.com/felangel/fresh/blob/master/packages/fresh_dio/lib/src/fresh.dart#L143).

But on [this line](https://github.com/felangel/fresh/blob/master/packages/fresh_dio/lib/src/fresh.dart#L164-L190) I think it's better to use copyWith to make it more readable and it will create new object, something like this
```dart
final requestOptions = response.requestOptions.copyWith();
requestOptions.headers = requestOptions.headers..addAll(_tokenHeader(refreshedToken));
_httpClient.fetch(requestOptions);
```

I believe `request` is also using `fetch` [under the hood](https://github.com/cfug/dio/blob/main/dio/lib/src/dio_mixin.dart#L371).

**Comment by felangel** [comment]
Closing this for now since the request is resent after a successful refresh. Feel free to file a new issue if you have any other feedback/improvements, thanks!
