### ISSUE TITLE
Can't run the example app

### ISSUE THREAD

**Issue by StefanYYC** [felangel/fresh#2]
Hi Felix, 
When I try to run the app I get the following errors : 
![image](https://user-images.githubusercontent.com/32258096/80352943-ec48cf80-8874-11ea-8e1a-0608fd200659.png)

![image](https://user-images.githubusercontent.com/32258096/80352996-02569000-8875-11ea-9e6c-0165f61cc30c.png)

So unfortunately the app can't run at all. I think in the Pull Request you did but not merge yet there might a fix to the problem since it seems to come from package dart:html mostly.
Lmk if I can help in any way!

**Comment by AbdOoSaed** [comment]
hi, Stefan, I found this issue and solve it 
the problem in -> dart:html
this package not working outside the browser

**Comment by AbdOoSaed** [comment]
I will make a pull request with the new code

**Comment by StefanYYC** [comment]
Yeah that's what I thought too and I think he corrected it but didn't merge the PR ! https://github.com/felangel/fresh/pull/1

**Comment by AbdOoSaed** [comment]
ya he did it by replacing   dart:html  with  dart:io

**Comment by StefanYYC** [comment]
So let's wait for the merge 😄

**Comment by felangel** [comment]
Hey @StefanYYC 👋
Thanks for opening an issue and sorry about that!

As you mentioned it’s fixed in the release/v0.0.1 branch and will be merged shortly.

**Comment by felangel** [comment]
Fixed in https://github.com/felangel/fresh/commit/1d6dac4caa6d3971705c8fd284effe7c6ee01340.

Closing for now but let me know if you're still experiencing difficulties running the example 👍
