### ISSUE TITLE
Dumping and re-sending requests which occurred while refreshing

### ISSUE THREAD

**Issue by vasilich6107** [felangel/fresh#29]
Hi. Thanks for your packages.
I looked through the packages and did not find handling of the case when additional requests occuring while refreshing is in progress. 
Technically it could lead to multiple refresh requests...
Some servers could apply blocking policy for the cases when `flood` refresh occurs.

May be I'm missing something...

Is this *by design* or *place for improvement*

**Comment by felangel** [comment]
Hi @vasilich6107 👋 
Thanks for opening an issue and for the positive feedback!

Are you able to share a sample app which reproduces the issue? I'm happy to take a closer look and update the package to account for this since it is definitely a place for improvement 😄

**Comment by vasilich6107** [comment]
I'm back with reproduction)

Here is a repo https://github.com/artflutter/fresh_repro

First of all let's start a demo server
go to `jwt_server` folder and run

`npm install`
`npm run example`

This will run a jwt server. There is also web interface for internal testing purposes http://localhost:12345/

Then launch `flutter` project.

There is 2 buttons `Login` and `protected`. Login - logs in user. Protected - launches request to token protected resource.
The tokens are managed via cookies but for the demo the actual way of token delivery to the server does not matter.

The initial token expiration is set to 1/6 of minute, 10 seconds.

In `main.dart` on line 79 you can tweak the refresh delay to simulate different scenarios.

**Comment by felangel** [comment]
@vasilich6107 thanks so much! I'll have a look asap 😄

**Comment by vasilich6107** [comment]
Let me describe two scenarios) In next two messages

**Comment by vasilich6107** [comment]
First scenario - refresh and request repeat.

How to reproduce:
- open console to see the logs
- token refresh delay should be `0`
- press `login`
- press `protected` several times until you see `refresh operation` message in console

There should be next message following `refresh operation` with `flutter: {"message":"Some protected data"}` cause after token refresh we need to resend failed request.

**Comment by vasilich6107** [comment]
Second scenario - multiple refresh request

How to reproduce
- make app hot restart to clear previous session if needed
- open console to see the logs
- token refresh delay should be 5000 (5 seconds)
- press `login`
- press `protected` "as fast as you can" to spawn multiple requests 
- there will be a tons of refresh token requests in console

There should be only one refresh token requests. All other should be paused and resended after token successfully refreshed.
https://tppr.me/RBZr3

**Comment by vasilich6107** [comment]
Hi @felangel 
Any news?

**Comment by felangel** [comment]
@vasilich6107 sorry for the delay I've been really busy with other work this week. I will have a fix this weekend 👍

**Comment by marcos930807** [comment]
Any news on this, the static analysis on this package is broken

**Comment by felangel** [comment]
This should be addressed as part of #39

**Comment by vasilich6107** [comment]
Hi @felangel 
This issue unfortunately is not fixed

https://user-images.githubusercontent.com/6721286/168859223-067f30c0-e559-4ef8-9152-30a8513d7f7e.mov

**Comment by vasilich6107** [comment]
@felangel any feedback?

**Comment by vasilich6107** [comment]
@felangel any news?

**Comment by felangel** [comment]
I think this should be resolved by #68. Will get that merged and published shortly

**Comment by vasilich6107** [comment]
Ok
Will check after merge
