### ISSUE TITLE
Remove limit to Web only with `dart:html`

### ISSUE THREAD

**Issue by magillus** [felangel/fresh#3]
![image](https://user-images.githubusercontent.com/729803/80375816-82bdc680-885e-11ea-8635-d20a2601f00d.png)

**Comment by magillus** [comment]
or even: `forbidden = 403;`

**Comment by felangel** [comment]
Hey @magillus thanks for opening an issue!
This is a duplicate of #2 and is fixed on the release branch. I’ll have it merged shortly 👍
