### ISSUE TITLE
fresh_graphql is incompatible with graphql_flutter 4.0.0-beta.3

### ISSUE THREAD

**Issue by FickleLife** [felangel/fresh#30]
When using `fresh_graphql: ^0.3.0` and `graphql_flutter: ^4.0.0-beta.3` I get in the console: 

```
Because every version of fresh_graphql depends on graphql ^3.0.2 and graphql_flutter 4.0.0-beta.3 depends on graphql ^4.0.0-beta.3, fresh_graphql is incompatible with graphql_flutter 4.0.0-beta.3.
And because no versions of graphql_flutter match >4.0.0-beta.3 <5.0.0, fresh_graphql is incompatible with graphql_flutter ^4.0.0-beta.3.
```
I guess a bump of the version of `graphql` that `fresh_graphql` uses is needed (or sit tight until 4.0.0 releases)? ~~Currently getting around it by overriding dependencies~~

```
dependency_overrides:
  graphql: ^4.0.0-beta.3
```
The app won't compile with the dependency override.

**Comment by felangel** [comment]
Hi @FickleLife 👋 
Thanks for opening an issue!

I've upgraded to the latest beta on #31 and have published `fresh_graphql v0.4.0-dev.1`.
Closing for now but feel free to open additional issues if you experience problems with the dev release and I will release v0.4.0 when the 4.0.0 release is out 👍
