### ISSUE TITLE
Package dependency should be updated

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [felangel/fresh#33]
I have this error when trying to use latest graphql_flutter: "Because graphql_flutter >=4.0.0 depends on graphql ^4.0.0 and fresh_graphql <0.4.0-dev.1 depends on graphql ^3.0.2, graphql_flutter >=4.0.0 is incompatible with fresh_graphql <0.4.0-dev.1."

**Comment by felangel** [comment]
Hi @vytautas-pranskunas- 👋 
Thanks for opening an issue!

I'll bump the dependency and publish shortly 👍

**Comment by vytautas-pranskunas-** [comment]
Would be awesome

**Comment by felangel** [comment]
Just published [fresh_graphql v4.0.0](https://pub.dev/packages/fresh_graphql) 🎉

**Comment by vytautas-pranskunas-** [comment]
Thanks
