### ISSUE TITLE
Can you upgrade dependencies for dio

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [felangel/fresh#34]
Today I have upgraded flutter and packages and finally i get this error:

```
Because fresh_dio 0.2.0 depends on dio ^3.0.9 and no versions of fresh_dio match >0.2.0 <0.3.0, fresh_dio ^0.2.0 requires dio ^3.0.9.

So, because senio_assist depends on both dio ^4.0.0-beta6 and fresh_dio ^0.2.0, version solving failed.
pub get failed (1; So, because senio_assist depends on both dio ^4.0.0-beta6 and fresh_dio ^0.2.0, version solving fa
```

**Comment by vytautas-pranskunas-** [comment]
Hi, i see you added pre-release. What blocks you from release?

**Comment by felangel** [comment]
> Hi, i see you added pre-release. What blocks you from release?

Hi 👋

Dio currently doesn’t have a stable release so I’m planning to release a stable version once dio does 👍
