### ISSUE TITLE
Does this package support sending multiple concurrent not valid access token at the same time ?

### ISSUE THREAD

**Issue by ahmedsalamay** [felangel/fresh#38]
Does this package support sending multiple concurrent not valid access token at the same time?
Scenario:
* Future.wait([apiCall1, apiCall2, apiCall3]);
* The three api calls has an expired access token

**Comment by felangel** [comment]
Hi @ahmedsalamay 👋 
Thanks for opening an issue!

Yes, this should be supported in the latest release 👍 

Feel free to file a bug if you experience any issues, thanks!
