### ISSUE TITLE
Can't finalize a finalized MultipartFile

### ISSUE THREAD

**Issue by MekniWassime** [felangel/fresh#52]
My team and i are working on a mobile app that sometimes requires us to send multiple images to a nodejs server using FormData and MutipartFiles (part of the dio package) and recently we had to transition from sessions and cookies to Jwt tokens. and the transition was really seamless thanks to your package that honestly saved me days of work at least
but i ran into a problem and here's the scenario for simplicity
   - i send a post request where data is of type *FormData* that contains multiple files or *MultipartFile*s
   - the token has expired so your package requests a new accessToken (as far as i understand)
   - a new accessToken is received and the request is resent
   - a Dio error is thrown `DioError [DioErrorType.other]: Bad state: Can't finalize a finalized MultipartFile.` (i will put the entire error message below) 

after doing some research on the matter i found out that you have to basically make a new FormData object out of the old FormData if you want to resend a request
a link of the most promising solution i found [https://github.com/flutterchina/dio/issues/482](https://github.com/flutterchina/dio/issues/482)
 here is how i implemented your interceptor

    static  final _fresh = Fresh.oAuth2(
	    tokenStorage: PersistantTokenStorage(),
	    refreshToken: (token, client) async {
	    print('refreshing token...');
	    try {
		    var response = await AuthService.getAcessToken(token?.refreshToken);
		    print("refresh response");
		    print(response);
		    String? newAccessToken = response['accessToken'];
		    if (newAccessToken == null)
			    throw RevokeTokenException();
		    return OAuth2Token(
			    accessToken: newAccessToken,
			    refreshToken: token?.refreshToken,
			   );
		    } catch (e) {
			    print(e);
			    throw RevokeTokenException();
		    }
	    },
    );
and here's the full error code with some of the `print`s that i did included (note that aside from MultipartFiles no other problem has occured

    I/flutter (10036): refreshing token...    
    I/flutter (10036): refresh token response = {accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjEwNjk4YmUzMDUxNTEzNjg4ZTRmMWIyIiwiZW1haWwiOiJ0dW5pc2lhbmNhbXBlcnNAZ21haWwuY29tIn0sImlhdCI6MTYzMDA5MTU1NSwiZXhwIjoxNjMwMDkxNTg1fQ.mU32DL3-b-pq_OyEyA4gdnhTrlE0tgXwSGjWGN-pfug}
    I/flutter (10036): refresh response
    I/flutter (10036): {accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjEwNjk4YmUzMDUxNTEzNjg4ZTRmMWIyIiwiZW1haWwiOiJ0dW5pc2lhbmNhbXBlcnNAZ21haWwuY29tIn0sImlhdCI6MTYzMDA5MTU1NSwiZXhwIjoxNjMwMDkxNTg1fQ.mU32DL3-b-pq_OyEyA4gdnhTrlE0tgXwSGjWGN-pfug}
    I/flutter (10036): saving token
    I/flutter (10036): DioError [DioErrorType.other]: Bad state: Can't finalize a finalized MultipartFile.
    I/flutter (10036): #0 FormData.finalize
    package:dio/src/form_data.dart:134
    I/flutter (10036): #1 DioMixin._transformData
    package:dio/src/dio_mixin.dart:706
    I/flutter (10036): #2 DioMixin._dispatchRequest
    package:dio/src/dio_mixin.dart:631
    I/flutter (10036): #3 DioMixin.fetch.<anonymous closure>
    package:dio/src/dio_mixin.dart:585
    I/flutter (10036): #4 DioMixin.fetch._requestInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>
    package:dio/src/dio_mixin.dart:502
    I/flutter (10036): #5 DioMixin.checkIfNeedEnqueue
    package:dio/src/dio_mixin.dart:795
    I/flutter (10036): #6 DioMixin.fetch._requestInterceptorWrapper.<anonymous closure>.<anonymous closure>
    package:dio/src/dio_mixin.dart:500
    I/flutter (10036): #7 new Future.<anonymous closure> (dart:async/future.dart:174:37)
    I/flutter (10036): #8 _rootRun (dart:async/zone.dart:1346:47)
    I/flutter (10036): #9 _CustomZone.run (dart:async/zone.dart:1258:19)
    I/flutter (10036): #10 _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
    I/flutter (10036): #11 _CustomZone.bindCallbackGuarded.<anonymous clos
some information about the environment and versions used

    environment:    
	    sdk: ">=2.12.0 <3.0.0"
	dependencies:
	    dio: ^4.0.0
	    fresh_dio: ^0.3.1

if more information could be provided i d be more than happy to provide them

**Comment by MekniWassime** [comment]
Thank you for the reply, although i m currently quite busy i will take a shot at making a reproduction sample
No promises though hope you understand

**Comment by enioluciano** [comment]
Hi
I'm facing same problem. When I upload photos in API, i get same error.

**Comment by faithomotoso** [comment]
@enioluciano Do you have a refresh token implementation?

**Comment by jeankpoti** [comment]
You can just reset the list in which you are storing the multipartfiles after the request is made.

**Comment by felangel** [comment]
Closing for now since this issue is quite old. If this is still an issue with the latest version let me know and I'm happy to revisit this 👍

**Comment by WingCH** [comment]
This solution worked for me:

```
class CustomDio extends DioForNative {
  CustomDio([super.options]);

  @override
  Future<Response<T>> request<T>(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    CancelToken? cancelToken,
    Options? options,
    ProgressCallback? onSendProgress,
    ProgressCallback? onReceiveProgress,
  }) async {
    // Issue: After refresh token, the form data will be finalized.
    // Dio API Error: DioException [unknown]: null
    // Error: Bad state: The FormData has already been finalized. This typically means you are using the same FormData in repeated requests.
    // https://github.com/cfug/dio/issues/482
    if (data is FormData) {
      FormData formData = FormData();
      formData.fields.addAll(data.fields);

      for (MapEntry mapFile in data.files) {
        if (mapFile.value is MultipartFile) {
          formData.files.add(MapEntry(mapFile.key, mapFile.value));
        }
      }
      data = formData;
    }

    return super.request<T>(
      path,
      data: data,
      queryParameters: queryParameters,
      cancelToken: cancelToken,
      options: options,
      onSendProgress: onSendProgress,
      onReceiveProgress: onReceiveProgress,
    );
  }
}
```

```
final fresh = Fresh.oAuth2(
      httpClient: CustomDio(dio.options),
      tokenStorage: TokenStorage(secureStorageService),
      refreshToken: (token, client) => _refreshToken(token),
      shouldRefresh: _shouldRefresh,
    );
```

**Comment by alex-melnyk** [comment]
> This solution worked for me:
> 
> ```
> class CustomDio extends DioForNative {
>   CustomDio([super.options]);
> 
>   @override
>   Future<Response<T>> request<T>(
>     String path, {
>     Object? data,
>     Map<String, dynamic>? queryParameters,
>     CancelToken? cancelToken,
>     Options? options,
>     ProgressCallback? onSendProgress,
>     ProgressCallback? onReceiveProgress,
>   }) async {
>     // Issue: After refresh token, the form data will be finalized.
>     // Dio API Error: DioException [unknown]: null
>     // Error: Bad state: The FormData has already been finalized. This typically means you are using the same FormData in repeated requests.
>     // https://github.com/cfug/dio/issues/482
>     if (data is FormData) {
>       FormData formData = FormData();
>       formData.fields.addAll(data.fields);
> 
>       for (MapEntry mapFile in data.files) {
>         if (mapFile.value is MultipartFile) {
>           formData.files.add(MapEntry(mapFile.key, mapFile.value));
>         }
>       }
>       data = formData;
>     }
> 
>     return super.request<T>(
>       path,
>       data: data,
>       queryParameters: queryParameters,
>       cancelToken: cancelToken,
>       options: options,
>       onSendProgress: onSendProgress,
>       onReceiveProgress: onReceiveProgress,
>     );
>   }
> }
> ```
> 
>  ```
> final fresh = Fresh.oAuth2(
>       httpClient: CustomDio(dio.options),
>       tokenStorage: TokenStorage(secureStorageService),
>       refreshToken: (token, client) => _refreshToken(token),
>       shouldRefresh: _shouldRefresh,
>     );
> ```

Thanks here is what I solved:

```dart
/// Handle request on the fly.
  void _handleRequest(
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) async {
    options
      ..extra = {
        RequestExtra.requestUuid.name: uuid.v4(),
        RequestExtra.requestedAt.name: DateTime.now().millisecondsSinceEpoch,
      }
      ..cancelToken ??= _sessionCancelToken;

    final requestString = _plainRequestOptions(options);
    AppLog.info('REQUEST $requestString');

    final requestData = options.data;

    if (requestData is FormData && requestData.isFinalized) {
      AppLog.info('FormData is finalized, cloning it to prevent errors.');
      return handler.next(
        options.copyWith(
          data: FormData()
            ..fields.addAll(requestData.fields)
            ..files.addAll(requestData.files),
        ),
      );
    }

    return handler.next(options);
  }
```
