### ISSUE TITLE
when dio version from 4.0.0 to 4.0.3 interceptor error

### ISSUE THREAD

**Issue by sqiao2-ford** [felangel/fresh#53]
../../../../.pub-cache/git/mobileapp-cn-components-service-0c9a9b528758740e21a494e36669d299535ffc7e/mobileapp_cn_core_networking/lib/mobileapp_cn_core_networking.dart:11:1: Error: Can't export this file because it contains a 'part of' declaration.
export 'package:dio/src/interceptor.dart';
^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.3/lib/src/interceptor.dart: Context: This is the file that can't be exported.

**Comment by felangel** [comment]
Can you please re-test with the latest version (v0.4.0) and let me know if it's still an issue? Closing for now but feel free to comment and I'm happy to revisit this if it's a problem in v0.4.0.
