### ISSUE TITLE
Auto retry after refresh token?

### ISSUE THREAD

**Issue by a7md0** [felangel/fresh#54]
Hello, I have been using fresh_dio package for a Dio http client. I was able to implement the `refreshToken` + `shouldRefresh` functions, and it is refreshing the token whenever the http call fail based on my conditions.

However, the initial fired request does fail. Is it possible to retry the request after refreshing the token? If not, what best approach to handle this? Should I create an interceptor which check the token expiration time before firing the request?

**Comment by vasilich6107** [comment]
@a7md0 it should retry the request with updated token based on this code
https://github.com/felangel/fresh/blob/master/packages/fresh_dio/lib/src/fresh.dart#L121
