### ISSUE TITLE
Request new Feature 

### ISSUE THREAD

**Issue by veldrict** [felangel/fresh#55]
Hi @felangel ,

I want to request a new Feature for fresh. I need to request the token before i got response error.
Which i need to check the request and token expired or not from the timestamp that i got from login.

Example for the json :

`
{
    "token" : "aZakRij123",
    "validUntil" : "2021-12-25T00:00:00"
}
`

**Comment by felangel** [comment]
Closing this since it's quite old and there isn't enough context. If this is still an issue feel free to file a new issue with additional information/context and I'm happy to continue the discussion 👍
