### ISSUE TITLE
not enough examples

### ISSUE THREAD

**Issue by SerdarYildiz06** [felangel/fresh#67]
Hey Felix, thanks for this repo. It is possible to make spesific example with reflesh token. This examples doesn't look like real time example. The title is reflesh token this cause  api should auth api but in this example the api irrelevant with auth.

**Comment by fikretsengul** [comment]
You can check my boilerplate to see a working example:

https://github.com/fikretsengul/flutter_advanced_boilerplate

Thank you for this awesome package @felangel

**Comment by felangel** [comment]
Happy to accept PRs linking to existing examples. Closing for now since this issue is quite old.
