### ISSUE TITLE
can't figure out how to use package!

### ISSUE THREAD

**Issue by imansoleymanzadeh** [felangel/fresh#73]
although I had reed the document and example but I cant figure out how to use the package 
there is lots of complexity in the code  . some one who dont know what is bloc and ... its hard to use and figure out how to  use
please make simpler example to understand

**Comment by felangel** [comment]
You can take a look at some other open source examples on GitHub. If you're still having trouble please let me know what aspects are confusing and I'm happy to take a closer look.

https://github.com/felangel/fresh/network/dependents
