### ISSUE TITLE
Updated package to use dio 5.0.0

### ISSUE THREAD

**Issue by MatyasK** [felangel/fresh#74]
They just released new dio version 5.0.0 and this package depends on dio version ^4.0.0.

**Comment by alejandrogiubel** [comment]
Please update. Thanks.

**Comment by felangel** [comment]
I should have time to do this in the next few days but feel free to open a PR sooner if you'd like and I'm happy to review it 👍

**Comment by MatyasK** [comment]
later today I might have time, but I can't promise it, if so I will make a pr

**Comment by mHassan20896** [comment]
I will do it

**Comment by MatyasK** [comment]
@mHassan20896 the pr is already waiting for approval:
https://github.com/felangel/fresh/pull/75

**Comment by akbulutdora** [comment]
> @mHassan20896 the pr is already waiting for approval: #75

@mHassan20896  waiting for this. afaik there is a security issue with dio below 5.0.0 so i want to update asap. thanks.

**Comment by felangel** [comment]
This is now done and available in [fresh_dio v0.4.0](https://pub.dev/packages/fresh_dio/versions/0.4.0), thanks everyone 🎉
