### ISSUE TITLE
Unhandled DioError on HTTP code 401

### ISSUE THREAD

**Issue by Dr4key** [felangel/fresh#9]
Hi @felangel Dio treats HTTP codes above 400 as DioError so the code in 
`Future<dynamic> onResponse(Response response) async { ... }` won't be executed when OAuth server responds with code 401. 
It should be handled in `Future<dynamic> onError(DioError error) async { ... }`.

Sorry if the issue is badly formatted, first one I ever wrote :)

**Comment by felangel** [comment]
Hey @Dr4key 👋
Thanks for opening an issue good call!

I’ll get a fix in ASAP 👍
