### ISSUE TITLE
[ Concurrent API calls ]

### ISSUE THREAD

**Issue by Gobmichet** [felangel/fresh#97]
Hi,
Thanks for the work,

What about concurrent calls ? I mean let's say for the exemple :

- I have a home_page.dart with 3 sections.
- Each section is filled with datas coming from separate / specific API calls.
- We then have smtg like this :
```
@override
  void initState() {
    super.initState();
    <ApiCall_1>
    <ApiCall_2>
    <ApiCall_3>
  }
```

Won't this provoke refresh tokens infinite loop ?
How to handle this ?
How does your lib handle this ?

'cause Queue.lock( ) / .unlock( ) that would intervene on [ Error  401 ("token-expired") ] would trigger too late so...

Thanks in advance (^_^)

**Comment by felangel** [comment]
Closing this for now but if this is still an issue please feel free to provide a link to a minimal reproduction sample that illustrates the issue and I'm happy to take a closer look, thanks!
